version: "2"
services:
  api:
    image: skatepark-api-go:latest
    ports:
      - "8080:8080"
    environment: 
      - ORIGIN_ALLOWED=
      - SKATEPARKS_FILE=./repository/json/skateparks.json
      - IMGUR_API_KEY
